/// Opcodes for the Hunnu bytecode VM
/// Matches the C VM opcodes in compiler/vm/opcodes.h
#[repr(u8)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum OpCode {
    Constant = 0,
    ConstantInt = 1,
    ConstantFloat = 2,
    ConstantString = 3,
    Nil = 4,
    True = 5,
    False = 6,
    Add = 7,
    Subtract = 8,
    Multiply = 9,
    Divide = 10,
    Modulo = 11,
    Greater = 12,
    Less = 13,
    GreaterEqual = 14,
    LessEqual = 15,
    Equal = 16,
    NotEqual = 17,
    Not = 18,
    Negate = 19,
    Jump = 20,
    JumpIfFalse = 21,
    JumpIfTrue = 22,
    Pop = 23,
    PopN = 24,
    GetLocal = 25,
    SetLocal = 26,
    GetGlobal = 27,
    SetGlobal = 28,
    CreateArray = 29,
    GetIndex = 30,
    SetIndex = 31,
    CreateString = 32,
    Call = 33,
    Return = 34,
    Halt = 35,
    DefineFn = 36,
}

impl OpCode {
    pub fn from_byte(byte: u8) -> Option<OpCode> {
        match byte {
            0 => Some(OpCode::Constant),
            1 => Some(OpCode::ConstantInt),
            2 => Some(OpCode::ConstantFloat),
            3 => Some(OpCode::ConstantString),
            4 => Some(OpCode::Nil),
            5 => Some(OpCode::True),
            6 => Some(OpCode::False),
            7 => Some(OpCode::Add),
            8 => Some(OpCode::Subtract),
            9 => Some(OpCode::Multiply),
            10 => Some(OpCode::Divide),
            11 => Some(OpCode::Modulo),
            12 => Some(OpCode::Greater),
            13 => Some(OpCode::Less),
            14 => Some(OpCode::GreaterEqual),
            15 => Some(OpCode::LessEqual),
            16 => Some(OpCode::Equal),
            17 => Some(OpCode::NotEqual),
            18 => Some(OpCode::Not),
            19 => Some(OpCode::Negate),
            20 => Some(OpCode::Jump),
            21 => Some(OpCode::JumpIfFalse),
            22 => Some(OpCode::JumpIfTrue),
            23 => Some(OpCode::Pop),
            24 => Some(OpCode::PopN),
            25 => Some(OpCode::GetLocal),
            26 => Some(OpCode::SetLocal),
            27 => Some(OpCode::GetGlobal),
            28 => Some(OpCode::SetGlobal),
            29 => Some(OpCode::CreateArray),
            30 => Some(OpCode::GetIndex),
            31 => Some(OpCode::SetIndex),
            32 => Some(OpCode::CreateString),
            33 => Some(OpCode::Call),
            34 => Some(OpCode::Return),
            35 => Some(OpCode::Halt),
            36 => Some(OpCode::DefineFn),
            _ => None,
        }
    }
}
